ignore:
  - __pycache__
  - __init__
  - .venv
  - .git
  - backup
module_summary_llm:
  model: qwen/qwen2.5-coder-14b
  base_url: "http://127.0.0.1:1234/v1"
  api_key: "dummy_key"
  provider: lmstudio # registered name through decorator
architecture_summary_llm:
  model: qwen/qwen2.5-coder-14b
  base_url: "http://127.0.0.1:1234/v1"
  api_key: "dummy_key"
  provider: lmstudio # registered name through decorator
readme_llm:
  model: qwen2.5-14b-instruct
  base_url: "http://127.0.0.1:1234/v1"
  api_key: "dummy_key"
  provider: lmstudio # registered name through decorator
docstring_llm:
  model: qwen2.5-14b-instruct
  base_url: "http://127.0.0.1:1234/v1"
  api_key: "dummy_key"
  provider: lmstudio # registered name through decorator
